name: HeyTaco for PR
description: Gives 🌮 in HeyTaco for merged PRs
author: victorx64
inputs:
  hey-taco-token:
    description: HeyTaco API token
    required: true
  season-start:
    description: Current season start date ("yyyy-MM-dd"). Can be in future.
    default: "2023-03-27"
    required: false
  git-pathspec:
    description: Pattern used to limit paths. See https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
    required: false
  min-additions:
    description: Required number of additions to count a PR. After update, also set `season-start` to today's date.
    required: false
    default: "1"
  xp-per-taco:
    description: Taco cost in XP. After update, also set `season-start` to today's date.
    required: false
    default: "75"

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      if: github.event_name == 'push'
      with:
        path: ${{ github.action_path }}/devrating.sqlite3
        key: season-${{ inputs.season-start }}.sqlite3-${{ github.run_id }}
        restore-keys: |
          season-${{ inputs.season-start }}.sqlite3-
    - uses: actions/checkout@v3
      if: github.event_name == 'push'
      with:
        fetch-depth: 0
    - run: |
        dotnet run --project ${{ github.action_path }}/src/Action.csproj -- `
        '${{ github.repository }}' `
        '${{ github.token }}' `
        '${{ github.workspace }}' `
        '${{ github.ref_name }}' `
        '${{ github.action_path }}/devrating.sqlite3' `
        '${{ github.sha }}' `
        '${{ inputs.min-additions }}' `
        '${{ inputs.season-start }}' `
        '${{ inputs.hey-taco-token }}' `
        '${{ inputs.xp-per-taco }}' `
        ${{ inputs.git-pathspec }}
      if: github.event_name == 'push'
      shell: pwsh
    - uses: actions/upload-artifact@v3
      if: github.event_name == 'push'
      with:
        name: taco-report.md
        path: |
          ${{ github.action_path }}/devrating.sqlite3

branding:
  icon: shopping-cart
  color: red
